development:
  adapter: postgresql
  encoding: unicode
  database: dwp_dev

test:
  adapter: postgresql
  encoding: unicode
  database: dwp_test

production:
  adapter: postgresql
  encoding: unicode
  database: dwp_prod
